/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/improvements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Improvements */
        post: operations["improvements_improvements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/improvements/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revisions */
        post: operations["revisions_improvements_revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Text */
        post: operations["analyze_text_analyze_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Files */
        post: operations["analyze_files_analyze_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Text Case */
        post: operations["create_text_case_cases_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Demo Case */
        post: operations["create_demo_case_cases_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_cases__case_id__get"];
        put?: never;
        post?: never;
        /** Delete Case */
        delete: operations["delete_case_cases__case_id__delete"];
        options?: never;
        head?: never;
        /** Update Case */
        patch: operations["update_case_cases__case_id__patch"];
        trace?: never;
    };
    "/cases/{case_id}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comparison */
        get: operations["comparison_cases__case_id__comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/files/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download File */
        get: operations["download_file_cases__case_id__files__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/files/{document_id}/pages/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page Image */
        get: operations["page_image_cases__case_id__files__document_id__pages__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/files/{document_id}/pages/{number}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Page */
        get: operations["search_page_cases__case_id__files__document_id__pages__number__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Analysis Id */
            analysis_id: string;
            /** Provider */
            provider: string;
            /** Documents */
            documents: components["schemas"]["Document"][];
            patent: components["schemas"]["Patent"];
            /** Rejections */
            rejections: components["schemas"]["Rejection"][];
            /** Impacts */
            impacts: components["schemas"]["Impact"][];
            graph: components["schemas"]["Graph"];
            /** Warnings */
            warnings: string[];
            /** Claim Statuses */
            claim_statuses?: components["schemas"]["ClaimDisposition"][];
            claim_summary?: components["schemas"]["ClaimSummary"];
            /** Citations */
            citations?: components["schemas"]["CitationDocument"][];
            /** Rejection Citations */
            rejection_citations?: components["schemas"]["RejectionCitation"][];
            /** Evidence Links */
            evidence_links?: {
                [key: string]: unknown;
            }[];
            /** Claim Version */
            claim_version?: {
                [key: string]: unknown;
            };
        };
        /** Basis */
        Basis: {
            /** Rejection Id */
            rejection_id: string;
            /** Statute */
            statute: string;
            /** Problem */
            problem: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** Body_analyze_files_analyze_files_post */
        Body_analyze_files_analyze_files_post: {
            /** Patent */
            patent: string;
            /** Office Action */
            office_action: string;
            /** References */
            references?: string[] | null;
            /** Amendments */
            amendments?: string[] | null;
            /** Version History */
            version_history?: string | null;
        };
        /** Body_create_case_cases_post */
        Body_create_case_cases_post: {
            /** Patent */
            patent: string;
            /** Office Action */
            office_action: string;
            /** References */
            references?: string[] | null;
            /** Amendments */
            amendments?: string[] | null;
            /** Version History */
            version_history?: string | null;
            /** Title */
            title?: string | null;
        };
        /** CaseUpdate */
        CaseUpdate: {
            /** Title */
            title?: string | null;
            /** Status */
            status?: ("open" | "in_progress" | "responded" | "closed") | null;
            /** Deadline */
            deadline?: string | null;
        };
        /** CitationDocument */
        CitationDocument: {
            /** Citation Id */
            citation_id: string;
            /** Canonical Key */
            canonical_key: string;
            /** Display Name */
            display_name: string;
            /** Authors */
            authors: string[];
            /** Title */
            title?: string | null;
            /** Publication Number */
            publication_number?: string | null;
            /** Doi */
            doi?: string | null;
            /** Journal */
            journal?: string | null;
            /** Year */
            year?: number | null;
            /**
             * Type
             * @enum {string}
             */
            type: "patent" | "npl" | "unknown";
            /**
             * Citation Role
             * @enum {string}
             */
            citation_role: "relied_upon" | "supporting_evidence" | "not_relied_upon";
            /** Citation Roles */
            citation_roles: string[];
            evidence: components["schemas"]["Evidence"];
            /** Source Document Id */
            source_document_id?: string | null;
        };
        /** CitedReference */
        CitedReference: {
            /** Citation Id */
            citation_id: string;
            /** Name */
            name: string | null;
            /** Publication Number */
            publication_number: string | null;
            evidence: components["schemas"]["Evidence"];
            definition_evidence?: components["schemas"]["Evidence"] | null;
            /**
             * Type
             * @default unknown
             * @enum {string}
             */
            type: "patent" | "npl" | "unknown";
            /**
             * Raw Text
             * @default
             */
            raw_text: string;
            /** Publication */
            publication?: string | null;
            /** Year */
            year?: number | null;
            /** Title */
            title?: string | null;
            /** Doi */
            doi?: string | null;
            /** Bibliographic Locator */
            bibliographic_locator?: string | null;
            /**
             * Canonical Key
             * @default
             */
            canonical_key: string;
            /**
             * Citation Role
             * @default relied_upon
             * @enum {string}
             */
            citation_role: "relied_upon" | "supporting_evidence" | "not_relied_upon";
            /**
             * Explicit Alias
             * @default false
             */
            explicit_alias: boolean;
            /** Source Document Id */
            source_document_id?: string | null;
        };
        /** Claim */
        Claim: {
            /** Claim Number */
            claim_number: number;
            /** Text */
            text: string;
            /** Independent */
            independent: boolean;
            /** Depends On */
            depends_on: number[];
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "canceled";
            evidence: components["schemas"]["Evidence"];
        };
        /** ClaimDisposition */
        ClaimDisposition: {
            /** Claim Number */
            claim_number: number;
            /**
             * Status
             * @enum {string}
             */
            status: "rejected" | "objected" | "allowed" | "withdrawn" | "canceled" | "pending" | "unknown";
            evidence?: components["schemas"]["Evidence"] | null;
            /**
             * Conditional Allowance
             * @default false
             */
            conditional_allowance: boolean;
            /**
             * Raw Status
             * @default
             */
            raw_status: string;
            /**
             * Source Status
             * @default
             */
            source_status: string;
        };
        /** ClaimImprovementSuggestion */
        ClaimImprovementSuggestion: {
            /** Claim Number */
            claim_number: number;
            /**
             * Jurisdiction
             * @enum {string}
             */
            jurisdiction: "us" | "kr";
            /** Issue Summary */
            issue_summary: string;
            /** Rejection Basis */
            rejection_basis: components["schemas"]["Basis"][];
            /** Element Comparison */
            element_comparison: components["schemas"]["ElementComparison"][];
            /** Strategies */
            strategies: components["schemas"]["Strategy"][];
            optional_example: components["schemas"]["Example"];
            /** Missing Evidence */
            missing_evidence: string[];
            /** Cautions */
            cautions: string[];
        };
        /** ClaimRevision */
        ClaimRevision: {
            /** Original Claim Number */
            original_claim_number: number;
            /** Revision Id */
            revision_id: string;
            /** Text */
            text: string;
            /** Text Hash */
            text_hash: string;
            /** Parent Revision Id */
            parent_revision_id: string | null;
            /** Created At */
            created_at: string;
        };
        /** ClaimSummary */
        ClaimSummary: {
            /** Direct Rejected Claims */
            direct_rejected_claims?: number[];
            /** Objected Claims */
            objected_claims?: number[];
            /** Allowed Claims */
            allowed_claims?: number[];
            /** Withdrawn Claims */
            withdrawn_claims?: number[];
            /** Canceled Claims */
            canceled_claims?: number[];
            /** Pending Claims */
            pending_claims?: number[];
            /** Unknown Claims */
            unknown_claims?: number[];
            /** Dependency Impacted Claims */
            dependency_impacted_claims?: number[];
        };
        /** Document */
        Document: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "patent" | "office_action" | "reference";
            /** Text */
            text: string;
            /** Pages */
            pages: components["schemas"]["Page"][];
            /** Warnings */
            warnings?: string[];
            metadata?: components["schemas"]["OCRMetadata"];
            /** Source Metadata */
            source_metadata?: {
                [key: string]: unknown;
            };
        };
        /** ElementComparison */
        ElementComparison: {
            /** Claim Element */
            claim_element: string;
            /** Examiner Position */
            examiner_position: string;
            /**
             * Assessment
             * @enum {string}
             */
            assessment: "examiner_asserted" | "not_verified";
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** ElementSupport */
        ElementSupport: {
            /** Element Id */
            element_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "SUPPORTED" | "PARTIALLY_SUPPORTED" | "NOT_FOUND" | "UNCERTAIN";
            /** Evidence Ids */
            evidence_ids: string[];
            /** Grounding */
            grounding: components["schemas"]["Grounding"][];
            /** Reason */
            reason: string;
        };
        /** Evidence */
        Evidence: {
            /** Document Id */
            document_id: string;
            /** Text */
            text: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Page Numbers */
            page_numbers: number[];
            /** Xml Path */
            xml_path?: string | null;
        };
        /** Example */
        Example: {
            /** Available */
            available: boolean;
            /** Text */
            text: string | null;
            /** Disclaimer */
            disclaimer: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Grounding */
            grounding: components["schemas"]["Grounding"][];
        };
        /** Graph */
        Graph: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "contains" | "directly_addresses" | "depends_on" | "cites";
            evidence?: components["schemas"]["Evidence"] | null;
            /** Citation Role */
            citation_role?: string | null;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "office_action" | "rejection" | "claim" | "citation";
            /**
             * Status
             * @default
             */
            status: string;
            /** Claim Number */
            claim_number?: number | null;
        };
        /** Grounding */
        Grounding: {
            /** Evidence Id */
            evidence_id: string;
            /** Quote */
            quote: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Impact */
        Impact: {
            /** Rejection Id */
            rejection_id: string;
            /** Direct Claims */
            direct_claims: number[];
            /** Objected Claims */
            objected_claims?: number[];
            /** Dependency Impacted Claims */
            dependency_impacted_claims: number[];
            /** Missing Claims */
            missing_claims: number[];
            /** Citations */
            citations: string[];
            /** Review Items */
            review_items?: components["schemas"]["ReviewItem"][];
        };
        /** ImprovementRequest */
        ImprovementRequest: {
            analysis: components["schemas"]["AnalysisResult"];
            /** Claim Number */
            claim_number: number;
            /** Rejection Id */
            rejection_id?: string | null;
            /**
             * Require Llm
             * @default false
             */
            require_llm: boolean;
        };
        /** ImprovementResponse */
        ImprovementResponse: {
            /** Analysis Id */
            analysis_id: string;
            /** Claim Number */
            claim_number: number;
            /** Rejection Id */
            rejection_id: string | null;
            /** Evidence Hash */
            evidence_hash: string;
            /** Provider */
            provider: string;
            /**
             * Status
             * @enum {string}
             */
            status: "review" | "limited" | "abstained";
            suggestion: components["schemas"]["ClaimImprovementSuggestion"];
            /** Sources */
            sources: components["schemas"]["ReviewEvidence"][];
            /** Limitations */
            limitations: string[];
        };
        /** OCRMetadata */
        OCRMetadata: {
            /** Pdf Parser */
            pdf_parser?: ("pymupdf" | "pdfium" | "pypdf") | null;
            /** Pdf Text Extractors */
            pdf_text_extractors?: {
                [key: string]: string;
            };
            /** Pdf Layout Pages */
            pdf_layout_pages?: number[];
            /**
             * Ocr Used
             * @default false
             */
            ocr_used: boolean;
            /** Ocr Pages */
            ocr_pages?: number[];
            /** Ocr Engine */
            ocr_engine?: "tesseract" | null;
            /** Ocr Renderer */
            ocr_renderer?: ("pymupdf" | "pdfium") | null;
            /** Ocr Dpi */
            ocr_dpi?: number | null;
            /** Ocr Language */
            ocr_language?: string | null;
            /** Ocr Raw Text */
            ocr_raw_text?: {
                [key: string]: string;
            };
            /** Removed Margins */
            removed_margins?: components["schemas"]["RemovedMargin"][];
            /** Ocr Words */
            ocr_words?: {
                [key: string]: components["schemas"]["OCRWord"][];
            };
        };
        /** OCRWord */
        OCRWord: {
            /** Text */
            text: string;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Block */
            block: number;
            /** Line */
            line: number;
            /** Confidence */
            confidence: number;
        };
        /** Page */
        Page: {
            /** Number */
            number: number;
            /** Text */
            text: string;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** Patent */
        Patent: {
            /** Document Id */
            document_id: string;
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Warnings */
            warnings?: string[];
        };
        /** Rejection */
        Rejection: {
            /** Rejection Id */
            rejection_id: string;
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "rejection" | "objection";
            /** Statute */
            statute: string;
            /** Claims */
            claims: number[];
            /** Primary Claims */
            primary_claims?: number[];
            /** Reason Summary */
            reason_summary: string;
            /** Examiner Explanation */
            examiner_explanation: string;
            /** Cited References */
            cited_references: components["schemas"]["CitedReference"][];
            evidence: components["schemas"]["Evidence"];
            /**
             * Extraction Method
             * @enum {string}
             */
            extraction_method: "local" | "openai" | "azure";
            /**
             * Statute Code
             * @default
             */
            statute_code: string;
            /**
             * Raw Statute Text
             * @default
             */
            raw_statute_text: string;
            /**
             * Subject
             * @default claims
             */
            subject: string;
        };
        /** RejectionCitation */
        RejectionCitation: {
            /** Rejection Id */
            rejection_id: string | null;
            /** Citation Id */
            citation_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "relied_upon" | "supporting_evidence" | "not_relied_upon";
            evidence: components["schemas"]["Evidence"];
            /** Claim Numbers */
            claim_numbers?: number[];
        };
        /** RejectionResponse */
        RejectionResponse: {
            /** Rejection Id */
            rejection_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "POTENTIALLY_ADDRESSES" | "PARTIALLY_ADDRESSES" | "DOES_NOT_ADDRESS" | "INSUFFICIENT_EVIDENCE";
            /** Reason */
            reason: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Grounding */
            grounding: components["schemas"]["Grounding"][];
            /**
             * Prior Art Assessment
             * @enum {string}
             */
            prior_art_assessment: "OA_ONLY" | "INSUFFICIENT_EVIDENCE" | "PROVIDED_EXCERPTS";
        };
        /** RemovedMargin */
        RemovedMargin: {
            /** Page Number */
            page_number: number;
            /** Text */
            text: string;
            /**
             * Position
             * @enum {string}
             */
            position: "header" | "footer";
            /** Reason */
            reason: string;
        };
        /** ReviewEvidence */
        ReviewEvidence: {
            /** Evidence Id */
            evidence_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "claim" | "parent_claim" | "office_action" | "status" | "specification" | "citation_mention" | "citation_original";
            /** Label */
            label: string;
            evidence: components["schemas"]["Evidence"];
            /** Navigation Item */
            navigation_item: string;
            /** Provenance */
            provenance?: ("examiner_explicit_evidence" | "system_retrieved_evidence") | null;
        };
        /** ReviewItem */
        ReviewItem: {
            /** Item Id */
            item_id: string;
            /** Rejection Id */
            rejection_id: string;
            /** Claim Numbers */
            claim_numbers: number[];
            /** Text */
            text: string;
            evidence: components["schemas"]["Evidence"];
        };
        /** RevisionAssessment */
        RevisionAssessment: {
            /** Revision Summary */
            revision_summary: string;
            /** Specification Support */
            specification_support: components["schemas"]["ElementSupport"][];
            /** Rejection Response */
            rejection_response: components["schemas"]["RejectionResponse"][];
            /** Remaining Issues */
            remaining_issues: string[];
            /** Cautions */
            cautions: string[];
        };
        /** RevisionElement */
        RevisionElement: {
            /** Element Id */
            element_id: string;
            /** Element */
            element: string;
            /**
             * Change Type
             * @enum {string}
             */
            change_type: "added" | "changed" | "unchanged";
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Candidate Evidence Ids */
            candidate_evidence_ids: string[];
        };
        /** RevisionRequest */
        RevisionRequest: {
            analysis: components["schemas"]["AnalysisResult"];
            /** Claim Number */
            claim_number: number;
            /** Rejection Id */
            rejection_id?: string | null;
            /**
             * Require Llm
             * @default false
             */
            require_llm: boolean;
            /** Revised Text */
            revised_text: string;
            /** Parent Revision Id */
            parent_revision_id?: string | null;
        };
        /** RevisionReview */
        RevisionReview: {
            /** Analysis Id */
            analysis_id: string;
            /** Rejection Id */
            rejection_id: string | null;
            /** Evidence Hash */
            evidence_hash: string;
            /** Cache Key */
            cache_key: string;
            /** Provider */
            provider: string;
            revision: components["schemas"]["ClaimRevision"];
            /** Claim Changes */
            claim_changes: components["schemas"]["TextChange"][];
            /** Elements */
            elements: components["schemas"]["RevisionElement"][];
            assessment: components["schemas"]["RevisionAssessment"];
            /** New Matter Risks */
            new_matter_risks: string[];
            similarity: components["schemas"]["Similarity"];
            /** Sources */
            sources: components["schemas"]["ReviewEvidence"][];
            /** Limitations */
            limitations: string[];
        };
        /** Similarity */
        Similarity: {
            /** Method */
            method: string;
            /** Original Claim */
            original_claim: number | null;
            /** Specification */
            specification: {
                [key: string]: number | null;
            };
            /** Note */
            note: string;
        };
        /** Strategy */
        Strategy: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Target Elements */
            target_elements: string[];
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "clarify" | "narrow" | "add_limitation" | "remove_unsupported_scope" | "dependency_rewrite" | "argument_only" | "other";
            /** Evidence Ids */
            evidence_ids: string[];
            /** Grounding */
            grounding: components["schemas"]["Grounding"][];
            /** Expected Effect */
            expected_effect: string;
            /** Tradeoff */
            tradeoff: string;
        };
        /** TextAnalysisRequest */
        TextAnalysisRequest: {
            /** Patent Text */
            patent_text: string;
            /** Office Action Text */
            office_action_text: string;
        };
        /** TextChange */
        TextChange: {
            /**
             * Change Type
             * @enum {string}
             */
            change_type: "added" | "removed" | "changed" | "unchanged";
            /** Original */
            original: string;
            /** Revised */
            revised: string;
            /** Original Start */
            original_start: number;
            /** Original End */
            original_end: number;
            /** Revised Start */
            revised_start: number;
            /** Revised End */
            revised_end: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    improvements_improvements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImprovementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImprovementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revisions_improvements_revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionReview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    analyze_text_analyze_text_post: {
        parameters: {
            query?: {
                jurisdiction?: "US" | "KR" | "us" | "kr";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_files_analyze_files_post: {
        parameters: {
            query?: {
                jurisdiction?: "US" | "KR" | "us" | "kr";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_files_analyze_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_case_cases_post: {
        parameters: {
            query?: {
                jurisdiction?: "US" | "KR" | "us" | "kr";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_case_cases_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_text_case_cases_text_post: {
        parameters: {
            query?: {
                jurisdiction?: "US" | "KR" | "us" | "kr";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_demo_case_cases_demo_post: {
        parameters: {
            query?: {
                jurisdiction?: "US" | "KR" | "us" | "kr";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_cases__case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comparison_cases__case_id__comparison_get: {
        parameters: {
            query: {
                claim: number;
                scope?: string;
            };
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_cases__case_id__files__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_image_cases__case_id__files__document_id__pages__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
                document_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_page_cases__case_id__files__document_id__pages__number__search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path: {
                case_id: number;
                document_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
